## Analisis Klasifikasi Keluhan Tweet @PosIndonesia menggunakan metode SVM (Support Vector Machine Split 

Memproses data yang sudah bersih (di preprocessing) :

In [2]:
import pandas as pd

df = pd.read_csv('Data/CleanDatasetStopwordStemmer.csv', header=0, names=['ID','label','tweet'])
df.head()

ID      label                                              tweet
0   1  terlambat  posindonesia kau sungguh sangat lot sekali cum...
1   2  terlambat   min resi sampai kapan yah koo lama bgt ga sampaj
2   3  terlambat  blm pernah pake next day telat minggu koq pali...
3   4  terlambat  barang ambil aja gak takut lama klu anter gpp ...
4   5  terlambat  paket no blm jg padahal pake pos express udah ...

## Proses Klasifikasi dengan SVM

Mengimport library yang diperlukan untuk klasifikasi dengan metode SVM

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import average_precision_score
from sklearn.metrics import precision_recall_curve
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import metrics
#SVM
from sklearn import svm
from sklearn.svm import LinearSVC
import time

Label

In [5]:
df.loc[df["label"]=='terlambat',"label"]=0
df.loc[df["label"]=='sistem',"label"]=1
df.loc[df["label"]=='gagal',"label"]=2
df.loc[df["label"]=='jaminan',"label"]=3
df.loc[df["label"]=='pelayanan',"label"]=4
df.loc[df["label"]=='respon',"label"]=5

df.head()

ID label                                              tweet
0   1     0  posindonesia kau sungguh sangat lot sekali cum...
1   2     0   min resi sampai kapan yah koo lama bgt ga sampaj
2   3     0  blm pernah pake next day telat minggu koq pali...
3   4     0  barang ambil aja gak takut lama klu anter gpp ...
4   5     0  paket no blm jg padahal pake pos express udah ...

In [6]:
df_x=df["tweet"]
df_y=df["label"]

X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=1)
#x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.3,random_state=3)
#x_train, x_val, y_train, y_val = train_test_split(df_x, df_y, test_size=0.1,random_state=3)

## Tunning parameter

In [4]:
from sklearn.svm import SVC

df=pd.read_csv('data/CleanDatasetStopwordStemmer.csv',sep=',', header=0,names=['id','label','tweet',],encoding="ISO-8859-1")

df.loc[df["label"]=='terlambat',"label"]=0
df.loc[df["label"]=='sistem',"label"]=1
df.loc[df["label"]=='gagal',"label"]=2
df.loc[df["label"]=='jaminan',"label"]=3
df.loc[df["label"]=='pelayanan',"label"]=4
df.loc[df["label"]=='respon',"label"]=5

df_x=df["tweet"]
df_y=df["label"]

cv=CountVectorizer()

## Linear (C)

In [12]:
C_range=[0.001,0.01,0.1,1,10,100,1000]
acc_score=[]

for c in C_range:
        x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2,random_state=3)
        
        x_traincv=cv.fit_transform(x_train)
        z=x_traincv.toarray()
        z
        vectorizer = TfidfVectorizer(min_df=1)
        X = vectorizer.fit_transform(df_x)
        idf = vectorizer._tfidf.idf_
        cv1=TfidfVectorizer(min_df=1,stop_words=[""])
        x_traincv1 = cv1.fit_transform(x_train)
        a=x_traincv1.toarray() 
        print("Parameter C")
        print c
        metode = svm.SVC(kernel='linear',C=c)
        y_train=y_train.astype('int')
        metode.fit(x_traincv1,y_train)
        print("---Support Vector-----")
        print metode.n_support_ 
        print("----------------------------------")
        x_testcv1=cv1.transform(x_test)
        pred=metode.predict(x_testcv1)
        actu=np.array(y_test).astype(None)
        count=0

        for i in range (len(pred)):
            if pred[i]==actu[i]:
                count=count +1
        count
        len(actu)

        akurasi=count/444.0*100
        acc_score.append(akurasi)
    
print("----------------------------------")
print("---Akurasi-----")
print acc_score

Parameter C
0.001
---Support Vector-----
[288 304 291 292 299 298]
----------------------------------
Parameter C
0.01
---Support Vector-----
[288 305 291 292 299 298]
----------------------------------
Parameter C
0.1
---Support Vector-----
[282 294 261 290 295 283]
----------------------------------
Parameter C
1
---Support Vector-----
[231 233 180 239 267 211]
----------------------------------
Parameter C
10
---Support Vector-----
[238 239 178 239 271 211]
----------------------------------
Parameter C
100
---Support Vector-----
[238 239 178 238 266 213]
----------------------------------
Parameter C
1000
---Support Vector-----
[238 239 178 238 266 213]
----------------------------------
----------------------------------
---Akurasi-----
[13.963963963963963, 13.963963963963963, 78.82882882882883, 87.61261261261262, 86.48648648648648, 86.48648648648648, 86.48648648648648]


## Polynomial c,d, dan gamma

In [6]:
degree=[2,3,4,5,6]
acc_score=[]

for d in degree:
        x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2,random_state=3)
        x_traincv=cv.fit_transform(x_train)
        z=x_traincv.toarray()
        z
        vectorizer = TfidfVectorizer(min_df=1)
        X = vectorizer.fit_transform(df_x)
        idf = vectorizer._tfidf.idf_
        cv1=TfidfVectorizer(min_df=1,stop_words=[""])
        x_traincv1 = cv1.fit_transform(x_train)
        a=x_traincv1.toarray() 
        print("Parameter Degree")
        print d
        metode = svm.SVC(kernel='poly', degree=d) 
        y_train=y_train.astype('int')
        metode.fit(x_traincv1,y_train)
        print("---Support Vector-----")
        print metode.n_support_ 
        print("----------------------------------")
        x_testcv1=cv1.transform(x_test)
        pred=metode.predict(x_testcv1)
        actu=np.array(y_test).astype(None)
        count=0

        for i in range (len(pred)):
            if pred[i]==actu[i]:
                count=count +1
        count
        len(actu)

        akurasi=count/444.0*100
        acc_score.append(akurasi)
print("----------------------------------")
print("---Akurasi-----")
print acc_score

Parameter Degree
2
---Support Vector-----
[288 308 291 292 299 298]
----------------------------------
Parameter Degree
3
---Support Vector-----
[288 308 291 292 299 298]
----------------------------------
Parameter Degree
4
---Support Vector-----
[288 308 291 292 299 298]
----------------------------------
Parameter Degree
5
---Support Vector-----
[288 308 291 292 299 298]
----------------------------------
Parameter Degree
6
---Support Vector-----
[288 308 291 292 299 298]
----------------------------------
----------------------------------
---Akurasi-----
[13.963963963963963, 13.963963963963963, 13.963963963963963, 13.963963963963963, 13.963963963963963]


In [17]:
C_range=[0.001,0.01,0.1,1,10,100,1000]
acc_score=[]

for c in C_range:
        x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2,random_state=3)
        x_traincv=cv.fit_transform(x_train)
        z=x_traincv.toarray()
        z
        vectorizer = TfidfVectorizer(min_df=1)
        X = vectorizer.fit_transform(df_x)
        idf = vectorizer._tfidf.idf_
        cv1=TfidfVectorizer(min_df=1,stop_words=[""])
        x_traincv1 = cv1.fit_transform(x_train)
        a=x_traincv1.toarray() 
        metode = svm.SVC(kernel='poly', C=c) 

        y_train=y_train.astype('int')
        metode.fit(x_traincv1,y_train)
        x_testcv1=cv1.transform(x_test)
        pred=metode.predict(x_testcv1)
        actu=np.array(y_test).astype(None)
        count=0

        for i in range (len(pred)):
            if pred[i]==actu[i]:
                count=count +1
        count
        len(actu)

        akurasi=count/444.0*100
        acc_score.append(akurasi)
print("Parameter C")    
print C_range
print("----------------------------------")
print acc_score

Parameter C
[0.001, 0.01, 0.1, 1, 10, 100, 1000]
----------------------------------
[13.963963963963963, 13.963963963963963, 13.963963963963963, 13.963963963963963, 13.963963963963963, 13.963963963963963, 13.963963963963963]


In [20]:
gamma_range=[0.001,0.01,0.1,1,10,100,1000]
acc_score=[]

for g in gamma_range:
        x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2,random_state=3)
        x_traincv=cv.fit_transform(x_train)
        z=x_traincv.toarray()
        z
        vectorizer = TfidfVectorizer(min_df=1)
        X = vectorizer.fit_transform(df_x)
        idf = vectorizer._tfidf.idf_
        cv1=TfidfVectorizer(min_df=1,stop_words=[""])
        x_traincv1 = cv1.fit_transform(x_train)
        a=x_traincv1.toarray() 
        metode = svm.SVC(kernel='poly', gamma=g) 

        y_train=y_train.astype('int')
        metode.fit(x_traincv1,y_train)
        x_testcv1=cv1.transform(x_test)
        pred=metode.predict(x_testcv1)
        actu=np.array(y_test).astype(None)
        count=0

        for i in range (len(pred)):
            if pred[i]==actu[i]:
                count=count +1
        count
        len(actu)

        akurasi=count/444.0*100
        acc_score.append(akurasi)
print("Parameter Gamma")  
print gamma_range
print("----------------------------------")
print acc_score

Parameter Gamma
[0.001, 0.01, 0.1, 1, 10, 100, 1000]
----------------------------------
[13.963963963963963, 13.963963963963963, 13.963963963963963, 75.0, 77.7027027027027, 77.7027027027027, 77.7027027027027]


In [21]:
gamma_range=[0.001,0.01,0.1,1,10,100,1000]
acc_score=[]

for g in gamma_range:
        x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2,random_state=3)
        x_traincv=cv.fit_transform(x_train)
        z=x_traincv.toarray()
        z
        vectorizer = TfidfVectorizer(min_df=1)
        X = vectorizer.fit_transform(df_x)
        idf = vectorizer._tfidf.idf_
        cv1=TfidfVectorizer(min_df=1,stop_words=[""])
        x_traincv1 = cv1.fit_transform(x_train)
        a=x_traincv1.toarray() 
        metode = svm.SVC(kernel='poly', gamma=g, degree=2) 

        y_train=y_train.astype('int')
        metode.fit(x_traincv1,y_train)
        x_testcv1=cv1.transform(x_test)
        pred=metode.predict(x_testcv1)
        actu=np.array(y_test).astype(None)
        count=0

        for i in range (len(pred)):
            if pred[i]==actu[i]:
                count=count +1
        count
        len(actu)

        akurasi=count/444.0*100
        acc_score.append(akurasi)
print("Parameter Gamma Degree= 2") 
print gamma_range
print("----------------------------------")
print acc_score

Parameter Gamma Degree= 2
[0.001, 0.01, 0.1, 1, 10, 100, 1000]
----------------------------------
[13.963963963963963, 13.963963963963963, 13.963963963963963, 85.58558558558559, 86.03603603603604, 86.03603603603604, 86.03603603603604]


## RBF c dan gamma

In [22]:
gamma_range=[0.001,0.01,0.1,1,10,100,1000]
acc_score=[]

for g in gamma_range:
    x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2,random_state=3)
    x_traincv=cv.fit_transform(x_train)
    z=x_traincv.toarray()
    vectorizer = TfidfVectorizer(min_df=1)
    X = vectorizer.fit_transform(df_x)
    idf = vectorizer._tfidf.idf_
    cv1=TfidfVectorizer(min_df=1,stop_words=[""])
    x_traincv1 = cv1.fit_transform(x_train)
    a=x_traincv1.toarray() 

    metode = svm.SVC(kernel='rbf', gamma=g) 
    y_train=y_train.astype('int')
    metode.fit(x_traincv1,y_train)
    x_testcv1=cv1.transform(x_test)
    pred=metode.predict(x_testcv1)
    actu=np.array(y_test).astype(None)
    count=0

    for i in range (len(pred)):
        if pred[i]==actu[i]:
            count=count +1
    count
    len(actu)

    akurasi=count/444.0*100
    acc_score.append(akurasi)
print("Parameter Gamma")   
print gamma_range
print("----------------------------------")
print acc_score

Parameter Gamma
[0.001, 0.01, 0.1, 1, 10, 100, 1000]
----------------------------------
[13.963963963963963, 13.963963963963963, 85.13513513513513, 88.28828828828829, 14.63963963963964, 13.73873873873874, 13.73873873873874]


In [23]:
C_range=[0.001,0.01,0.1,1,10,100,1000]
acc_score=[]

for c in C_range:
    x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2,random_state=3)
    x_traincv=cv.fit_transform(x_train)
    z=x_traincv.toarray()
    vectorizer = TfidfVectorizer(min_df=1)
    X = vectorizer.fit_transform(df_x)
    idf = vectorizer._tfidf.idf_
    cv1=TfidfVectorizer(min_df=1,stop_words=[""])
    x_traincv1 = cv1.fit_transform(x_train)
    a=x_traincv1.toarray() 
    # linear SVM
    metode = svm.SVC(kernel='rbf', C=c) 
    y_train=y_train.astype('int')
    metode.fit(x_traincv1,y_train)
    x_testcv1=cv1.transform(x_test)
    pred=metode.predict(x_testcv1)
    actu=np.array(y_test).astype(None)
    count=0

    for i in range (len(pred)):
        if pred[i]==actu[i]:
            count=count +1
    count
    len(actu)

    akurasi=count/444.0*100
    acc_score.append(akurasi)
print("Parameter C") 
print C_range
print("----------------------------------")
print acc_score

Parameter C
[0.001, 0.01, 0.1, 1, 10, 100, 1000]
----------------------------------
[13.963963963963963, 13.963963963963963, 13.963963963963963, 13.963963963963963, 13.963963963963963, 55.63063063063063, 88.06306306306307]
